### ISSUE TITLE
Suggestions: Workshop material

### ISSUE THREAD

**Issue by lisaychuang** [FrontEndFoxes/workshops#66] opened 2019-04-20 19:43 UTC
Hi team,

As I work through the workshop material, I'll like to suggest some improvements that will help newcomers (like myself) to understand the material better. I'll update this issue as I go through each chapter.

## [Chapter 1: Introducing the My Pet Shop Web App](https://github.com/VueVixens/docs/blob/master/workshop/full-day/ch1.md)

- [ ] Adding `Vuetify` as a dependency [(line211)](https://github.com/VueVixens/docs/blame/43043ab31a376d5ebac58ed71d1004eecf608751/workshop/ch1.md#L211)

Refer to issue #65 , I had some issues with adding `Vuetify` as a dependency in Codesandbox.  I was able to debug and fix this once I changed the dependency to lowercase `vuetify`. This should be corrected in CH1 tutorial.

- [ ]  Vue class bindings [(line 306)](https://github.com/VueVixens/docs/blame/master/workshop/full-day/ch1.md#L306)

It will be helpful to give some context prior to introducing data binding as a new concept. For example, including an edited paragraph from VueJS guides in [Class and Style Bindings](https://vuejs.org/v2/guide/class-and-style.html):

> A common need for data binding is manipulating an element’s class list and its inline styles. Since they are both attributes, we can use `v-bind` to handle them.

And link out to both VueJS guide and [`v-bind`](https://vuejs.org/v2/api/#v-bind) API doc for reference. Additionally, I only learned that `:class` is the [shorthand](https://vuejs.org/v2/guide/syntax.html#v-bind-Shorthand) for `v-bind:class` after searching through the guides.  It will be helpful to introduce both syntaxes since learners may see both styles used in the wild.

- [ ] Using `code syntax` consistently throughout doc

In addition to the above point on `v-bind`, it will be helpful to review the docs for consistent use of `code syntax`:
- `v-bind` on [line 306](https://vuejs.org/v2/guide/syntax.html#v-bind-Shorthand)
- `:` shorthand on [line 306](https://vuejs.org/v2/guide/syntax.html#v-bind-Shorthand)
- Standardizing component names, e.g.
  - 'home' component [(line33)](https://github.com/VueVixens/docs/blame/43043ab31a376d5ebac58ed71d1004eecf608751/workshop/ch1.md#L33)
  - `<HelloWorld>` component [(line 35)](https://github.com/VueVixens/docs/blame/43043ab31a376d5ebac58ed71d1004eecf608751/workshop/ch1.md#L35)
  - HelloWorld.vue component [(line 332)](https://github.com/VueVixens/docs/blame/43043ab31a376d5ebac58ed71d1004eecf608751/workshop/ch1.md#L332)

- [ ] `v-on` directive for click event listener [(line 354)](https://github.com/VueVixens/docs/blame/43043ab31a376d5ebac58ed71d1004eecf608751/workshop/ch1.md#L354)

Similar to `v-bind` above, it will be helpful to link out to the VueJS guide on [`v-bind` shorthand](https://vuejs.org/v2/guide/syntax.html#v-on-Shorthand) and [API docs](https://vuejs.org/v2/api/#v-on),  and to note that the shorthand for `v-on` is `@`.

Reading through the VueJS guides on [event handling](https://vuejs.org/v2/guide/events.html), the guide walks through 4 examples of how `v-on` can be used:
  - simple inline JavaScript statement (e.g. `"counter += 1"`)
  - binding to a method name (e.g. `"greet"`) 
  - use methods in inline JavaScript statement (e.g. `"say('hi')"`)
  - use `$event` variable to access DOM elements (`"warn('Form cannot be submitted yet.', $event)"`)

In CH1 tutorial, it will be helpful to note that the example is using `@click` with a simple inline JavaScript statement `"themeSwitched = !themeSwitched"` but there are other options available (link out to VueJS guide).

**Comment by NataliaTepluhina** [comment] 2019-04-24 04:59
Thank you for your suggestions! I've added comments on them.

>I had some issues with adding Vuetify as a dependency in Codesandbox. I was able to debug and fix this once I changed the dependency to lowercase vuetify. This should be corrected in CH1 tutorial.

I can't reproduce this on any environment I have but since the change is literally one character, I think we can make it :sweat_smile: 

>It will be helpful to give some context prior to introducing data binding as a new concept

It's stated explicitly: `We can use v-bind directive or its shortcut :`. I don't mind adding a note paragraph with quick explanation/link to docs but I prefer it to be easier than given in the issue.

>Standardizing component names, e.g.

In the first case 'home' used not as a component name (it's `App.vue`) but as an explanation that this component is root one. In the second case, `HelloWorld` is shown with its use in the template as a tag, that's why we have a tag syntax. Third case refers to the file containing component, that's why it's `HelloWorld.vue`.

>there are other options available (link out to VueJS guide

We learn these options from next chapters. Listing them all immediately at chapter 1 might create a cognitive overload. I will leave it as it is for now.

**Comment by lisaychuang** [comment] 2019-04-24 19:34
Thanks @NataliaTepluhina for your comments, my suggestions were from a perspective of someone new to Vue following along with the tutorial. I felt it would have been beneficial to have some context for `v-bind, v-on` etc. Again, just my 2cents :)

**Comment by jlooper** [comment] 2019-07-10 15:59
Closing, thank you for the feedback

**Closed as completed by jlooper** 2019-07-10 15:59 UTC
